:revealjsdir: ../../node_modules/reveal.js
:revealjs_customtheme: ../../theme/vsfi.css


= Git & GitOps

Сергей Ларченко

== Системы контроля версий
[.notes]
--
- RCS (англ. Revision Control System) — одна из самых первых систем управления версиями, разработанная в 1982 году. 
- CVS (англ. Concurrent Versions System — система одновременных версий) — централизованная система управления версиями, популярная в 1990-е — начале 2000-х годов. 
- Subversion[8] (также известная как «SVN»[9]) — свободная централизованная система управления версиями, официально выпущенная в 2004 году компанией CollabNet[en]. С 2010 года Subversion является одним из проектов Apache Software Foundation и официально называется Apache Subversion (зарегистрированный товарный знак[10]). 
- Mercurial (с англ. — «ртутный, подвижный»), он же Hg (от обозначения химического элемента ртути) — кроссплатформенная распределённая система управления версиями, разработанная для эффективной работы с очень большими репозиториями кода. В первую очередь она является консольной программой. 
- Также известны как Distributed Version Control System, DVCS. Такие системы используют распределённую модель вместо традиционной клиент-серверной. Они, в общем случае, не нуждаются в централизованном хранилище: вся история изменения документов хранится на каждом компьютере, в локальном хранилище, и при необходимости отдельные фрагменты истории локального хранилища синхронизируются с аналогичным хранилищем на другом компьютере. В некоторых таких системах локальное хранилище располагается непосредственно в каталогах рабочей копии. 
- Git (произносится «гит»[7]) — распределённая система управления версиями. Проект был создан Линусом Торвальдсом для управления разработкой ядра Linux, первая версия выпущена 7 апреля 2005 года. На сегодняшний день его поддерживает Джунио Хамано. 
--
- RCS (Revision Control System)
- CVS (англ. Concurrent Versions System) 
- Subversion (также известная как "SVN") 
- DVCS (Distributed Version Control System)
- Mercurial
- Bazaar
- Git


== Git
[.notes]
--
- Нижний уровень git является так называемой контентно-адресуемой файловой системой.
- Ядро Git представляет собой набор утилит командной строки с параметрами. Все настройки хранятся в текстовых файлах конфигурации. Такая реализация делает Git легко портируемым на любую платформу и даёт возможность легко интегрировать Git в другие системы (в частности, создавать графические git-клиенты с любым желаемым интерфейсом). 
--

- Децентрализованный
- Для большой команды
- Поддержка множества веток
- Работа поверх SSH HTTP TCP
- Легко интегрируется с другими системами

== Сервера Git
[.notes]
--
- Все представленно можно установить у себя
- Есть веб интерфейсы
--

- Gogs
- Gitea
- Onedev
- Gitlab CE
- Gitolite

== Типовая схема работы с гитом

- `git init` Создание репозитория
- `git add README.md` Добавление файлов в индекс
- `git commit -m "chore: added README.md"` Коммит
- `git checkout -b mybranch` создание ветки
- `git checkout master or git switch master`  переключение между ветками

== Типовая схема работы с гитом

- `git merge master` слияние веток
- `git pull origin master` получение изменений из удаленного репозитория
- `git push origin master` отправка изменений в удаленный репозиторий
- `git diff` просмотр текущих не зафиксированных изменений

== GitOps

```
DevOps GitOpe = IaC + MR + CI/CD
```

== IaC

Инфраструктура как код:

* Описание инфраструктуры на каком либо DSL
* Автоматизированное обнвление\создание сущностей
* Единая точка с истиной (Git репозиторий)

== MR
[.notes]
--
- Расказать про тесты и линтеры
- Рассказать про необходимость ревью
--

- Запросы на слияние 
- Pull Requests
- Мержи и тому подобное )

== CI/CD

- Автоматизация сборки
- Автоматизация деплоя
- Автоматизация доставки приложения

== Что решает GitOps

== Утилиты

- FluxCD
- ArgoCD
- JenkinsX
- Terragrunt
- Helm Operator
- werf
- Any CI/CD
