:revealjsdir: ../../node_modules/reveal.js
:revealjs_customtheme: ../../theme/vsfi.css
:revealjs_showSlideNumber: all


= Ansible и управление конфигурацией

Сергей Ларченко

== Управление конфигурацией
[.notes]
--
программы и программные комплексы, позволяющие централизованно управлять конфигурацией множества разнообразных разрозненных операционных систем и прикладного программного обеспечения, работающего в них. 
--
- Минимизация ручных операций
- Воспроизводимость результата
- Конфигурация как код

=== Первая волна
[.notes]
--
Представлена в 1993 году
Для автоматизации управления большого количества компьютерных систем
--

- CFEngine

=== Вторая волна
[.notes]
--
Сложные системы с конфигурацией на руби. 

Шеф часто используют локально например гитлаб

--

- Chef
- Puppet 

=== Третья волна

[.notes]
--
Деление на волны условность, новая волна попытка решить пробелмы прошлой.

Написаны на питоне имеют похожие архитектуры

--

- Ansible
- SaltStack 

== Ansible
[.notes]
--
* одна из популярных систем 
--
== Возможности
- Установка и настройка ПО
- Работа с облачными провайдерами
- Работа с файлами
- Работа с сетью
- Сборка информации об ОС
- Простая разработка новых модулей

== Плюсы и минусы
[.notes]
--
* Любая системе имеет как плюсы так и минусы
* Упомянть про простоту установки
--
=== Плюсы
* Простота использования
* Написано на Python
* Без агентная модель
* Простой DSL на базе YAML
* Большой набор готовых ролей (Ansible Galaxy)

=== Минусы

[.notes]
--
* Уточнить про причиные медленной работы
* Уточнить про интерфейсы
* Уточнить про агентов
--
- CLI only
- Нет понятия состояния
- Слабая поддержка Windows
- Медленная работа на большой инфраструктуре
- Без агентная модель


== Inventory

* группы
* переменные
* вложенные группы

=== Формат хранения

[.notes]
--
Рассказать про генераторы инвентори
--
* ini
* yaml
* динамический

=== INI формат

[.notes]
--
Группы переменные вложенность групп
--
```ini
[global_server]
example.com hostname=example.com

[local_server]
mail hostname=mail.corp

[servers:children]
global_server
local_server
```

=== YAML формат

[.notes]
--
большая гибкость при генерации
--
```yaml
global_server:
  hosts:
    example.com:
      hostname: example.com

local_server:
  hosts:
    mail:
      hostname: mail.corp
servers:
  children:
    global_server:
    local_server:
```

== Playbooks
[.notes]
--
* Упомянуть возможность применять к нескольким группам
* Стратегии
--
- Описывает конфигурацию
- Управляет последовательностью настройки
- Описывает стратегию применения настроек

=== Пример плейбука
```yaml
- hosts: all
  roles:
    - myrole
  tasks:
    - name: ping
      ping:
```

== Роли
[.notes]
--
* Упомянуть про galaxy 
--
- Группировка тасков
- Преносимость
- Возможность автоматизированного тестирования

=== Структуру роли
```
common/           
  tasks/          #
    main.yml      #  <-- Список тасков 
  handlers/       #
    main.yml      #  <-- Хендлеры
  templates/      #  <-- Шаблоны
    ntp.conf.j2   #  
  files/          #
    bar.txt       #  <-- файлы используемые без имзенений 
  vars/           #
    main.yml      #  <-- Переменные не изменяемые извне
  defaults/       #
    main.yml      #  <-- дефолтные переменные доступные к изменению 
  meta/           #
    main.yml      #  <-- метаданные и зависимости
```

== Вопросы?

