:revealjsdir: ../../node_modules/reveal.js
:revealjs_customtheme: ../../theme/vsfi.css


= Kubernetes

Сергей Ларченко

== Что это?
[.notes]
--
Основные разработчики первых версий внутренней системы Google — программисты Джо Беда (Joe Beda), Брендан Бёрнс (Brendan Burns) и Крэйг Маклаки (Craig McLuckie[8]), в дальнейшем к проекту присоединились их коллеги Брайан Грант (Brian Grant) и Тим Хокин (Tim Hockin). Основной язык программирования системы — Go. На разработку и внутреннюю идеологию Kubernetes серьёзно повлиял другой продукт Google, оставшийся внутренней разработкой — система управления кластерами Google Borg[9][10], над которым ранее работал ряд ключевых разработчиков Kubernetes.
--

Оркестратор для контейнеров. Был разработан Google и передан сообществу. 

== Основные концепции

=== node (узел)
[.notes]
--
это отдельная физическая или виртуальная машина, на которой развёрнуты и выполняются контейнеры приложений. Каждый узел в кластере содержит сервисы для запуска приложений в контейнерах (например Docker), а также компоненты, предназначенные для централизованного управления узлом. 
--

Отдельная машина на которой идет щапуск всех контейнеров.

=== pod (под)
[.notes]
--
Под (pod, с англ. — «стручок, кокон», также модуль) — базовая единица для запуска и управления приложениями: один или несколько контейнеров, которым гарантирован запуск на одном узле, обеспечивается разделение ресурсов[15] и межпроцессное взаимодействие и предоставляется уникальный в пределах кластера IP-адрес[16]. Последнее позволяет приложениям, развёрнутым на поде, использовать фиксированные и предопределённые номера портов без риска конфликта. Поды могут напрямую управляться с использованием API Kubernetes или управление ими может быть передано контроллеру[15]. 
--
Базовая еденица для запуска приложения внутри kubernetes. Может содержать более одного контейнера

=== volume (Том)
[.notes]
--
Том (volume) — общий ресурс хранения для совместного использования из контейнеров, развёрнутых в пределах одного пода. 
--

Общий ресурс для общего хранения данных.

=== label (метка)
[.notes]
--
Все объекты управления (узлы, поды, контейнеры) в Kubernetes помечаются метками (label), селекторы меток (label selector) — это запросы, которые позволяют получить ссылку на объекты, соответствующие какой-то из меток[15]. Метки и селекторы — это главный механизм Kubernetes, который позволяет выбрать, какой из объектов следует использовать для запрашиваемой операции. 
--

Все объекты управления помечаются метками. Метки используются для выборки объектов.

=== controller(контроллер)
[.notes]
--
Контроллер (controller) — это процесс, который управляет состоянием кластера, пытаясь привести его от фактического состояния к желаемому[18]; он делает это, оперируя набором подов, определяемых с помощью селекторов меток и являющихся частью определения контроллера[19]. Выполнение контроллеров обеспечивается компонентом Kubernetes Controller Manager. Один из типов контроллеров, самый известный — это контроллер репликации (Replication Controller), который обеспечивает масштабирование, запуская указанное количество копий пода в кластере. Он также обеспечивает запуск новых экземпляров пода в том случае, если узел, на котором работает управляемый этим контроллером под, выходит из строя[18]. Другие контроллеры, входящие в основную систему Kubernetes, включают в себя «DaemonSet Controller», который обеспечивает запуск пода на каждой машине (или подмножеством машин), и «Job Controller» для запуска подов, которые выполняются до завершения, например, как часть пакетного задания. 
--

Отвечает за приведение кластера к заданному состоянию. 

=== operators(операторы)

[.notes]
--
Операторы (operators) — специализированный вид программного обеспечения Kubernetes, предназначенный для включения в кластер сервисов, сохраняющих своё состояние между выполнениями (stateful), таких как СУБД, системы мониторинга или кэширования[20]. Назначение операторов — предоставить возможность управления stateful-приложениями в кластере Kubernetes прозрачным способом и скрыть подробности их настроек от основного процесса управления кластером Kubernetes. 
--

Используется для управления statefull приложениями

== Архитектура

image::components-of-kubernetes.svg[Kubernetes]

=== Компоненты 

[.notes]
--
- Расказать про тесты и линтеры
- Рассказать про необходимость ревью
--

- etcd
- api server
- Controller manager 
- scheduler
- kubelet
- kube-proxy
- CNI

=== etcd
[.notes]
--
Etcd[en] — компонент подсистемы управления, отвечающий за согласованное хранение конфигурационных данных кластера, в некотором смысле — распределённый эквивалент каталога /etc Unix-систем. Реализован как легковесная распределённая NoSQL-СУБД класса «ключ — значение»; создан в рамках проекта CoreOS. 
--
- Отвечает за хранение конфигурации кластера.
- Работает в виде кластера
- NoSQL база данных

=== api server
[.notes]
--
Сервер API — ключевой компонент подсистемы управления, предоставляющий API в стиле REST (с использованием коммуникации в формате JSON поверх HTTP-транспорта), и используемый для организации внешнего и внутреннего доступа к функциям Kubernetes[15]. Сервер API обновляет состояние объектов, хранящееся в etcd, позволяя своим клиентам управлять распределением контейнеров и нагрузки между узлами управляемой системы. 
--

- Обеспечивает доступ к функциям Kubernetes
- Обновляет состояние объектов

=== scheduler
[.notes]
--
Планировщик (scheduler) — компонент подсистемы управления, который выбирает, на каком узле должен выполняться конкретный под, опираясь на критерии доступности ресурсов. Планировщик отслеживает использование ресурсов на каждом из узлов, обеспечивая распределение нагрузки так, чтобы она не превышала доступный объём ресурсов. Для этой цели планировщик должен обладать информацией о доступных на каждом из узлов ресурсах, требованиях к ним со стороны управляемых подов, а также различных дополнительных пользовательских ограничениях и политиках, таких как QoS, требования аффинитета и антиаффинитета (affinity — anti-affinity — связки или развязки объектов управления друг с другом), локализации данных[en]. Иными словами, роль планировщика — находить и предоставлять ресурсы в зависимости от запросов, возникающих в связи с загрузкой[22]. 
--

- отвечает за выбор размещения дла подов
- отслеживает потребление ресурсов

=== controller manager
[.notes]
--
Менеджер контроллеров (controller manager) — процесс, выполняющий основные контроллеры Kubernetes, такие как DaemonSet Controller и Replication Controller. Контроллеры взаимодействуют с сервером API Kubernetes, создавая, обновляя и удаляя управляемые ими ресурсы (поды, точки входа в сервисы и другие). 
--

- Отвечает за работу основных контроллеров
* DaemonSet Controller
* Replication Controller

=== Kubelet
[.notes]
--
Kubelet отвечает за статус выполнения подов на узле — отслеживает, корректно ли выполняется каждый из контейнеров, находясь в рабочем состоянии. Kubelet обеспечивает запуск, остановку и управление контейнерами приложений, организованными в поды. Функционально Kubelet можно рассматривать как аналог supervisord[15][23]. Если обнаруживается, что какой-то из подов находится в неверном состоянии, компонент пытается осуществить его повторное развёртывание и перезапуск на узле. Статус самого узла отправляется на подсистему управления каждые несколько секунд в форме диагностических сообщений (heartbeat message). Если мастер-узел, исходя из содержания этих сообщений или их отсутствия, обнаруживает, что конкретный узел не работает должным образом, процесс подсистемы управления Replication Controller пытается перезапустить необходимые поды на другом узле, находящемся в рабочем состоянии. 
--

- Управляем подами на узле
- Отслеживает состояние подово на узле

=== kube-proxy
[.notes]
--
Kube-proxy — компонент, являющийся комбинацией сетевого прокси-сервера и балансировщика нагрузки. Реализованные в нём операции сетевого уровня используют абстракцию сервиса[15]. Он отвечает за маршрутизацию входящего трафика на конкретные контейнеры, работающие в пределах пода, расположенного на узле. Маршрутизация обеспечивается на основе IP-адреса и порта входящего запроса. 
--

- Балансировка нагрузка
- Проксирование запросов

=== Container runtime 
[.notes]
--
the container runtime is the software that is responsible for running containers.
Kubernetes supports container runtimes such as containerd, CRI-O, and any other implementation of the Kubernetes CRI (Container Runtime Interface
--

Среда исполнения контейнеров

- containerd
- CRI-O

== Запуск приложения в kubernetes

=== Deployments
[.notes]
--
A Deployment provides declarative updates for Pods and ReplicaSets.

You describe a desired state in a Deployment, and the Deployment Controller changes the actual state to the desired state at a controlled rate. You can define Deployments to create new ReplicaSets, or to remove existing Deployments and adopt all their resources with new Deployments.
--

Предоставляет декларативный формат обновления подов и ReplicaSets

=== Deployments пример
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
----

=== ReplicaSets
[.notes]
--
A ReplicaSet's purpose is to maintain a stable set of replica Pods running at any given time. As such, it is often used to guarantee the availability of a specified number of identical Pods.
--
- Отвечает за масштабирование подов
- Следить что бы все реплики были запущены

=== StatefulSets
[.notes]
--
StatefulSet is the workload API object used to manage stateful applications.
--
- Стабильные, уникальные сетевые идентификаторы.
- Стабильное, постоянное хранилище.
- Упорядоченное, изящное развертывание и масштабирование.
- Упорядоченные автоматические скользящие обновления.

=== DaemonSet
[.notes]
--
A DaemonSet ensures that all (or some) Nodes run a copy of a Pod. As nodes are added to the cluster, Pods are added to them. As nodes are removed from the cluster, those Pods are garbage collected. Deleting a DaemonSet will clean up the Pods it created.
--

Запускает копии пода на каждой ноде кластера

=== Job
[.notes]
--
A Job creates one or more Pods and will continue to retry execution of the Pods until a specified number of them successfully terminate. As pods successfully complete, the Job tracks the successful completions. When a specified number of successful completions is reached, the task (ie, Job) is complete. Deleting a Job will clean up the Pods it created. Suspending a Job will delete its active Pods until the Job is resumed again.
--

Запускет под который выполняет задачу и останавливается

=== CronJob
[.notes]
--
A CronJob creates Jobs on a repeating schedule.

One CronJob object is like one line of a crontab (cron table) file. It runs a job periodically on a given schedule, written in Cron format.
--

Создает Job по расписанию.

== Дистрибутивы

- deckhouse
- k0s
- k3s
- k8s
- minikube
- rancher
- talos
